spring:
  datasource:
    url: jdbc:postgresql://localhost:55433/activitydetectordb
    username: user
    password: password

logging:
  level:
    com.actdet.backend: DEBUG

activity-detector:
  controllers:
    show-error-details-in-response: true

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE